; Generated by KLFC 1.5.7
; https://github.com/39aldo39/klfc

#MaxHotkeysPerInterval 200
#MaxThreadsPerHotkey 10

SendUps(ByRef modifiers) {
  for index, modifier in modifiers {
    if (modifier == "Caps")
      SetCapsLockState, off
    else if (modifier == "Num")
      SetNumLockState, off
    else if InStr(modifier, "Extend")
      %modifier% := false
    else
      Send {%modifier% Up}
  }
  modifiers := Object()
}

SendAsUnicode(string) {
  Result := ""
  Loop, Parse, string
    Result .= Format("{{}U+{:04x}{}}", Ord(A_LoopField))
  Send {Blind}%Result%
}

DeadKeys := ComObjCreate("Scripting.Dictionary")

DeadKey(baseChar, table, name := "") {
  Global ActiveDeadKey
  if (ActiveDeadKey != "") {
    NewActiveDeadKey := ComObjCreate("Scripting.Dictionary")
    for key in table {
      value := table.item(key)
      NewActiveDeadKey.item(key) := ActiveDeadKey.item(value)
    }
    result := ActiveDeadKey.item(name)
    if (IsObject(result)) {
      for key in result {
        value := result.item(key)
        NewActiveDeadKey.item(key) := value
      }
    } else if (result != "") {
      ActiveDeadKey := ""
      SendAsUnicode(result)
      Return
    }
    ActiveDeadKey := NewActiveDeadKey
    Return
  }
  ActiveDeadKey := table
  Input key, L1, {Esc}{F1}{F2}{F3}{F4}{F5}{F6}{F7}{F8}{F9}{F10}{F11}{F12}{Left}{Right}{Up}{Down}{Home}{End}{PgUp}{PgDn}{Del}{Ins}{BS}{PrintScreen}{Pause}{AppsKey}
  If InStr(ErrorLevel, "EndKey:") {
    ActiveDeadKey := ""
    value := SubStr(ErrorLevel, 8)
    Send {Blind}{%value%}
    SendAsUnicode(baseChar)
  } else if (ErrorLevel != "NewInput") {
    value := ActiveDeadKey.item(key)
    ActiveDeadKey := ""
    if (IsObject(value)) {
      DeadKey(baseChar, value)
    } else if (value != "") {
      SendAsUnicode(value)
    } else {
      SendAsUnicode(baseChar . key)
    }
  }
}

*SC029::Send {Blind}{VKc0SC029 DownR} ; QWERTY ~: ~
*SC029 up::Send {Blind}{VKc0SC029 Up}
*SC002::Send {Blind}{VK31SC002 DownR} ; QWERTY 1: 1
*SC002 up::Send {Blind}{VK31SC002 Up}
*SC003::Send {Blind}{VK32SC003 DownR} ; QWERTY 2: 2
*SC003 up::Send {Blind}{VK32SC003 Up}
*SC004::Send {Blind}{VK33SC004 DownR} ; QWERTY 3: 3
*SC004 up::Send {Blind}{VK33SC004 Up}
*SC005::Send {Blind}{VK34SC005 DownR} ; QWERTY 4: 4
*SC005 up::Send {Blind}{VK34SC005 Up}
*SC006::Send {Blind}{VK35SC006 DownR} ; QWERTY 5: 5
*SC006 up::Send {Blind}{VK35SC006 Up}
*SC007::Send {Blind}{VK36SC007 DownR} ; QWERTY 6: 6
*SC007 up::Send {Blind}{VK36SC007 Up}
*SC008::Send {Blind}{VK37SC008 DownR} ; QWERTY 7: 7
*SC008 up::Send {Blind}{VK37SC008 Up}
*SC009::Send {Blind}{VK38SC009 DownR} ; QWERTY 8: 8
*SC009 up::Send {Blind}{VK38SC009 Up}
*SC00a::Send {Blind}{VK39SC00a DownR} ; QWERTY 9: 9
*SC00a up::Send {Blind}{VK39SC00a Up}
*SC00b::Send {Blind}{VK30SC00b DownR} ; QWERTY 0: 0
*SC00b up::Send {Blind}{VK30SC00b Up}
*SC00c::Send {Blind}{VKbdSC00c DownR} ; QWERTY -: -
*SC00c up::Send {Blind}{VKbdSC00c Up}
*SC00d::Send {Blind}{VKbbSC00d DownR} ; QWERTY +: +
*SC00d up::Send {Blind}{VKbbSC00d Up}
*SC010::Send {Blind}{VK51SC010 DownR} ; QWERTY Q: Q
*SC010 up::Send {Blind}{VK51SC010 Up}
*SC011::Send {Blind}{VK57SC011 DownR} ; QWERTY W: W
*SC011 up::Send {Blind}{VK57SC011 Up}
*SC012::Send {Blind}{VK45SC012 DownR} ; QWERTY E: E
*SC012 up::Send {Blind}{VK45SC012 Up}
*SC013::Send {Blind}{VK52SC013 DownR} ; QWERTY R: R
*SC013 up::Send {Blind}{VK52SC013 Up}
*SC014::Send {Blind}{VK54SC014 DownR} ; QWERTY T: T
*SC014 up::Send {Blind}{VK54SC014 Up}
*SC015::Send {Blind}{VK59SC015 DownR} ; QWERTY Y: Y
*SC015 up::Send {Blind}{VK59SC015 Up}
*SC016::Send {Blind}{VK55SC016 DownR} ; QWERTY U: U
*SC016 up::Send {Blind}{VK55SC016 Up}
*SC017::Send {Blind}{VK49SC017 DownR} ; QWERTY I: I
*SC017 up::Send {Blind}{VK49SC017 Up}
*SC018::Send {Blind}{VK4fSC018 DownR} ; QWERTY O: O
*SC018 up::Send {Blind}{VK4fSC018 Up}
*SC019::Send {Blind}{VK50SC019 DownR} ; QWERTY P: P
*SC019 up::Send {Blind}{VK50SC019 Up}
*SC01a::Send {Blind}{VKdbSC01a DownR} ; QWERTY [: [
*SC01a up::Send {Blind}{VKdbSC01a Up}
*SC01b::Send {Blind}{VKddSC01b DownR} ; QWERTY ]: ]
*SC01b up::Send {Blind}{VKddSC01b Up}
*SC01e::Send {Blind}{VK41SC01e DownR} ; QWERTY A: A
*SC01e up::Send {Blind}{VK41SC01e Up}
*SC01f::Send {Blind}{VK53SC01f DownR} ; QWERTY S: S
*SC01f up::Send {Blind}{VK53SC01f Up}
*SC020::Send {Blind}{VK44SC020 DownR} ; QWERTY D: D
*SC020 up::Send {Blind}{VK44SC020 Up}
*SC021::Send {Blind}{VK46SC021 DownR} ; QWERTY F: F
*SC021 up::Send {Blind}{VK46SC021 Up}
*SC022::Send {Blind}{VK47SC022 DownR} ; QWERTY G: G
*SC022 up::Send {Blind}{VK47SC022 Up}
*SC023::Send {Blind}{VK48SC023 DownR} ; QWERTY H: H
*SC023 up::Send {Blind}{VK48SC023 Up}
*SC024::Send {Blind}{VK4aSC024 DownR} ; QWERTY J: J
*SC024 up::Send {Blind}{VK4aSC024 Up}
*SC025::Send {Blind}{VK4bSC025 DownR} ; QWERTY K: K
*SC025 up::Send {Blind}{VK4bSC025 Up}
*SC026::Send {Blind}{VK4cSC026 DownR} ; QWERTY L: L
*SC026 up::Send {Blind}{VK4cSC026 Up}
*SC027::Send {Blind}{VKbaSC027 DownR} ; QWERTY ;: ;
*SC027 up::Send {Blind}{VKbaSC027 Up}
*SC028::Send {Blind}{VKc0SC028 DownR} ; QWERTY ': ~
*SC028 up::Send {Blind}{VKc0SC028 Up}
*SC02b::Send {Blind}{VKdeSC02b DownR} ; QWERTY \: '
*SC02b up::Send {Blind}{VKdeSC02b Up}
*SC02c::Send {Blind}{VK5aSC02c DownR} ; QWERTY Z: Z
*SC02c up::Send {Blind}{VK5aSC02c Up}
*SC02d::Send {Blind}{VK58SC02d DownR} ; QWERTY X: X
*SC02d up::Send {Blind}{VK58SC02d Up}
*SC02e::Send {Blind}{VK43SC02e DownR} ; QWERTY C: C
*SC02e up::Send {Blind}{VK43SC02e Up}
*SC02f::Send {Blind}{VK56SC02f DownR} ; QWERTY V: V
*SC02f up::Send {Blind}{VK56SC02f Up}
*SC030::Send {Blind}{VK42SC030 DownR} ; QWERTY B: B
*SC030 up::Send {Blind}{VK42SC030 Up}
*SC031::Send {Blind}{VK4eSC031 DownR} ; QWERTY N: N
*SC031 up::Send {Blind}{VK4eSC031 Up}
*SC032::Send {Blind}{VK4dSC032 DownR} ; QWERTY M: M
*SC032 up::Send {Blind}{VK4dSC032 Up}
*SC033::Send {Blind}{VKbcSC033 DownR} ; QWERTY ,: ,
*SC033 up::Send {Blind}{VKbcSC033 Up}
*SC034::Send {Blind}{VKbeSC034 DownR} ; QWERTY .: .
*SC034 up::Send {Blind}{VKbeSC034 Up}
*SC035::Send {Blind}{VKbfSC035 DownR} ; QWERTY /: /
*SC035 up::Send {Blind}{VKbfSC035 Up}
*SC039::Send {Blind}{VK20SC039 DownR} ; QWERTY Space: Space
*SC039 up::Send {Blind}{VK20SC039 Up}
*SC056::Send {Blind}{VKdcSC056 DownR} ; QWERTY Iso: \
*SC056 up::Send {Blind}{VKdcSC056 Up}
*SC053::Send {Blind}{VK6eSC053 DownR} ; QWERTY KP_Dec: KP_Dec
*SC053 up::Send {Blind}{VK6eSC053 Up}

; QWERTY ~
#if
SC029::Send {Blind}{U+0060} ; `
+SC029::Send {Blind}{U+007c} ; |
>!<^SC029::Send {Blind}{U+00ac} ; ¬
+>!<^SC029::Send {Blind}{U+007c} ; |

; QWERTY 1
#if
SC002::Send {Blind}{U+0031} ; 1
+SC002::Send {Blind}{U+0021} ; !
>!<^SC002::Send {Blind}{U+00a1} ; ¡
+>!<^SC002::Send {Blind}{U+203d} ; ‽

; QWERTY 2
#if
SC003::Send {Blind}{U+0032} ; 2
+SC003::Send {Blind}{U+0022} ; "
>!<^SC003::Send {Blind}{U+02c8} ; ˈ
+>!<^SC003::Send {Blind}{U+02cc} ; ˌ

; QWERTY 3
#if
SC004::Send {Blind}{U+0033} ; 3
+SC004::Send {Blind}{U+00a3} ; £
>!<^SC004::Send {Blind}{U+025b} ; ɛ
+>!<^SC004::Send {Blind}{U+025c} ; ɜ

; QWERTY 4
#if
SC005::Send {Blind}{U+0034} ; 4
+SC005::Send {Blind}{U+0024} ; $
>!<^SC005::Send {Blind}{U+20ac} ; €
+>!<^SC005::Send {Blind}{U+20ab} ; ₫

; QWERTY 5
#if
SC006::Send {Blind}{U+0035} ; 5
+SC006::Send {Blind}{U+0025} ; %
>!<^SC006::Send {Blind}{U+0294} ; ʔ
+>!<^SC006::Return

; QWERTY 6
#if
SC007::Send {Blind}{U+0036} ; 6
+SC007::Send {Blind}{U+005e} ; ^
>!<^SC007::Send {Blind}{U+03b4} ; δ
+>!<^SC007::Send {Blind}{U+0394} ; Δ

; QWERTY 7
#if
SC008::Send {Blind}{U+0037} ; 7
+SC008::Send {Blind}{U+0026} ; &
>!<^SC008::Send {Blind}{U+028a} ; ʊ
+>!<^SC008::Return

; QWERTY 8
#if
SC009::Send {Blind}{U+0038} ; 8
+SC009::Send {Blind}{U+002a} ; *
>!<^SC009::Send {Blind}{U+035c} ; ͜
+>!<^SC009::Send {Blind}{U+0361} ; ͡

; QWERTY 9
#if
SC00a::Send {Blind}{U+0039} ; 9
+SC00a::Send {Blind}{U+0028} ; (
>!<^SC00a::Send {Blind}{U+0261} ; ɡ
+>!<^SC00a::Send {Blind}{U+27e9} ; ⟩

; QWERTY 0
#if
SC00b::Send {Blind}{U+0030} ; 0
+SC00b::Send {Blind}{U+0029} ; )
>!<^SC00b::
; ̛
if (DeadKeys.item("̛") == "") {
  DeadKeys.item("̛") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("̛").item("o") := "ơ"
  DeadKeys.item("̛").item("u") := "ư"
  DeadKeys.item("̛").item("O") := "Ơ"
  DeadKeys.item("̛").item("U") := "Ư"
  DeadKeys.item("̛").item(" ") := "̛"
}
DeadKey("̛", DeadKeys.item("̛"), "cdk:̛")
Return
+>!<^SC00b::
; ̊
if (DeadKeys.item("̊") == "") {
  DeadKeys.item("̊") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("̊").item("a") := "å"
  DeadKeys.item("̊").item("u") := "ů"
  DeadKeys.item("̊").item("w") := "ẘ"
  DeadKeys.item("̊").item("A") := "Å"
  DeadKeys.item("̊").item("U") := "Ů"
  DeadKeys.item("̊").item("y") := "ẙ"
  DeadKeys.item("̊").item(" ") := "̊"
}
DeadKey("̊", DeadKeys.item("̊"), "cdk:̊")
Return

; QWERTY -
#if
SC00c::Send {Blind}{U+002d} ; -
+SC00c::Send {Blind}{U+005f} ; _
>!<^SC00c::
; ̂
if (DeadKeys.item("̂") == "") {
  DeadKeys.item("̂") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("̂").item("a") := "â"
  DeadKeys.item("̂").item("e") := "ê"
  DeadKeys.item("̂").item("o") := "ô"
  DeadKeys.item("̂").item("A") := "Â"
  DeadKeys.item("̂").item("E") := "Ê"
  DeadKeys.item("̂").item("O") := "Ô"
  DeadKeys.item("̂").item(" ") := "̂"
}
DeadKey("̂", DeadKeys.item("̂"), "cdk:̂")
Return
+>!<^SC00c::Send {Blind}{U+2014} ; —

; QWERTY +
#if
SC00d::Send {Blind}{U+003d} ; =
+SC00d::Send {Blind}{U+002b} ; +
>!<^SC00d::
; ̆
if (DeadKeys.item("̆") == "") {
  DeadKeys.item("̆") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("̆").item("a") := "ă"
  DeadKeys.item("̆").item("A") := "Ă"
  DeadKeys.item("̆").item(" ") := "̆"
}
DeadKey("̆", DeadKeys.item("̆"), "cdk:̆")
Return
+>!<^SC00d::Send {Blind}{U+2248} ; ≈

; QWERTY Q
#if
SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0071} ; q
} else {
  Send {Blind}{U+0051} ; Q
}
Return
+SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0051} ; Q
} else {
  Send {Blind}{U+0071} ; q
}
Return
>!<^SC010::Send {Blind}{U+0251} ; ɑ
+>!<^SC010::Send {Blind}{U+0251} ; ɑ

; QWERTY W
#if
SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0077} ; w
} else {
  Send {Blind}{U+0057} ; W
}
Return
+SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0057} ; W
} else {
  Send {Blind}{U+0077} ; w
}
Return
>!<^SC011::Send {Blind}{U+0289} ; ʉ
+>!<^SC011::Send {Blind}{U+0289} ; ʉ

; QWERTY E
#if
SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0065} ; e
} else {
  Send {Blind}{U+0045} ; E
}
Return
+SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0045} ; E
} else {
  Send {Blind}{U+0065} ; e
}
Return
>!<^SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0259} ; ə
} else {
  Send {Blind}{U+02de} ; ˞
}
Return
+>!<^SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+02de} ; ˞
} else {
  Send {Blind}{U+0259} ; ə
}
Return

; QWERTY R
#if
SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0072} ; r
} else {
  Send {Blind}{U+0052} ; R
}
Return
+SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0052} ; R
} else {
  Send {Blind}{U+0072} ; r
}
Return
>!<^SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0279} ; ɹ
} else {
  Send {Blind}{U+02b4} ; ʴ
}
Return
+>!<^SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+02b4} ; ʴ
} else {
  Send {Blind}{U+0279} ; ɹ
}
Return

; QWERTY T
#if
SC014::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0074} ; t
} else {
  Send {Blind}{U+0054} ; T
}
Return
+SC014::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0054} ; T
} else {
  Send {Blind}{U+0074} ; t
}
Return
>!<^SC014::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+03b8} ; θ
} else {
}
Return
+>!<^SC014::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+03b8} ; θ
}
Return

; QWERTY Y
#if
SC015::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0079} ; y
} else {
  Send {Blind}{U+0059} ; Y
}
Return
+SC015::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0059} ; Y
} else {
  Send {Blind}{U+0079} ; y
}
Return
>!<^SC015::Send {Blind}{U+0153} ; œ
+>!<^SC015::Send {Blind}{U+0153} ; œ

; QWERTY U
#if
SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0075} ; u
} else {
  Send {Blind}{U+0055} ; U
}
Return
+SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0055} ; U
} else {
  Send {Blind}{U+0075} ; u
}
Return
>!<^SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0275} ; ɵ
} else {
  Send {Blind}{U+028a} ; ʊ
}
Return
+>!<^SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+028a} ; ʊ
} else {
  Send {Blind}{U+0275} ; ɵ
}
Return

; QWERTY I
#if
SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0069} ; i
} else {
  Send {Blind}{U+0049} ; I
}
Return
+SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0049} ; I
} else {
  Send {Blind}{U+0069} ; i
}
Return
>!<^SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+026a} ; ɪ
} else {
  Send {Blind}{U+028a} ; ʊ
}
Return
+>!<^SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+028a} ; ʊ
} else {
  Send {Blind}{U+026a} ; ɪ
}
Return

; QWERTY O
#if
SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006f} ; o
} else {
  Send {Blind}{U+004f} ; O
}
Return
+SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004f} ; O
} else {
  Send {Blind}{U+006f} ; o
}
Return
>!<^SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0254} ; ɔ
} else {
  Send {Blind}{U+27e8} ; ⟨
}
Return
+>!<^SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+27e8} ; ⟨
} else {
  Send {Blind}{U+0254} ; ɔ
}
Return

; QWERTY P
#if
SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0070} ; p
} else {
  Send {Blind}{U+0050} ; P
}
Return
+SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0050} ; P
} else {
  Send {Blind}{U+0070} ; p
}
Return
>!<^SC019::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+27e9} ; ⟩
}
Return
+>!<^SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+27e9} ; ⟩
} else {
}
Return

; QWERTY [
#if
SC01a::Send {Blind}{U+005b} ; [
+SC01a::Send {Blind}{U+007b} ; {
>!<^SC01a::
; ̃
if (DeadKeys.item("̃") == "") {
  DeadKeys.item("̃") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("̃").item("n") := "ñ"
  DeadKeys.item("̃").item("N") := "Ñ"
  DeadKeys.item("̃").item("l") := "ɫ"
  DeadKeys.item("̃").item("L") := "Ɫ"
  DeadKeys.item("̃").item(" ") := "̃"
}
DeadKey("̃", DeadKeys.item("̃"), "cdk:̃")
Return
+>!<^SC01a::
; ̄
if (DeadKeys.item("̄") == "") {
  DeadKeys.item("̄") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("̄").item("d") := "đ"
  DeadKeys.item("̄").item("D") := "Đ"
  DeadKeys.item("̄").item("a") := "ā"
  DeadKeys.item("̄").item("æ") := "ǣ"
  DeadKeys.item("̄").item("e") := "ē"
  DeadKeys.item("̄").item("i") := "ī"
  DeadKeys.item("̄").item("o") := "ō"
  DeadKeys.item("̄").item("u") := "ū"
  DeadKeys.item("̄").item("y") := "ȳ"
  DeadKeys.item("̄").item("A") := "Ā"
  DeadKeys.item("̄").item("Æ") := "Ǣ"
  DeadKeys.item("̄").item("E") := "Ē"
  DeadKeys.item("̄").item("I") := "Ī"
  DeadKeys.item("̄").item("O") := "Ō"
  DeadKeys.item("̄").item("U") := "Ū"
  DeadKeys.item("̄").item("Y") := "Ȳ"
  DeadKeys.item("̄").item(" ") := "̄"
}
DeadKey("̄", DeadKeys.item("̄"), "cdk:̄")
Return

; QWERTY ]
#if
SC01b::Send {Blind}{U+005d} ; ]
+SC01b::Send {Blind}{U+007d} ; }
>!<^SC01b::Send {Blind}{U+0309} ; ̉
+>!<^SC01b::
; ̈
if (DeadKeys.item("̈") == "") {
  DeadKeys.item("̈") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("̈").item("a") := "ä"
  DeadKeys.item("̈").item("e") := "ë"
  DeadKeys.item("̈").item("i") := "ï"
  DeadKeys.item("̈").item("o") := "ö"
  DeadKeys.item("̈").item("u") := "ü"
  DeadKeys.item("̈").item("w") := "ẅ"
  DeadKeys.item("̈").item("y") := "ÿ"
  DeadKeys.item("̈").item("A") := "Ä"
  DeadKeys.item("̈").item("E") := "Ë"
  DeadKeys.item("̈").item("I") := "Ï"
  DeadKeys.item("̈").item("O") := "Ö"
  DeadKeys.item("̈").item("U") := "Ü"
  DeadKeys.item("̈").item("W") := "Ẅ"
  DeadKeys.item("̈").item("Y") := "Ÿ"
  DeadKeys.item("̈").item(" ") := "̈"
}
DeadKey("̈", DeadKeys.item("̈"), "cdk:̈")
Return

; QWERTY A
#if
SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0061} ; a
} else {
  Send {Blind}{U+0041} ; A
}
Return
+SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0041} ; A
} else {
  Send {Blind}{U+0061} ; a
}
Return
>!<^SC01e::Send {Blind}{U+00e6} ; æ
+>!<^SC01e::Send {Blind}{U+00e6} ; æ

; QWERTY S
#if
SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0073} ; s
} else {
  Send {Blind}{U+0053} ; S
}
Return
+SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0053} ; S
} else {
  Send {Blind}{U+0073} ; s
}
Return
>!<^SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0283} ; ʃ
} else {
}
Return
+>!<^SC01f::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+0283} ; ʃ
}
Return

; QWERTY D
#if
SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0064} ; d
} else {
  Send {Blind}{U+0044} ; D
}
Return
+SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0044} ; D
} else {
  Send {Blind}{U+0064} ; d
}
Return
>!<^SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00f0} ; ð
} else {
  Send {Blind}{U+0257} ; ɗ
}
Return
+>!<^SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0257} ; ɗ
} else {
  Send {Blind}{U+00f0} ; ð
}
Return

; QWERTY F
#if
SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0066} ; f
} else {
  Send {Blind}{U+0046} ; F
}
Return
+SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0046} ; F
} else {
  Send {Blind}{U+0066} ; f
}
Return
>!<^SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+03b8} ; θ
} else {
}
Return
+>!<^SC021::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+03b8} ; θ
}
Return

; QWERTY G
#if
SC022::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0067} ; g
} else {
  Send {Blind}{U+0047} ; G
}
Return
+SC022::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0047} ; G
} else {
  Send {Blind}{U+0067} ; g
}
Return
>!<^SC022::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0263} ; ɣ
} else {
}
Return
+>!<^SC022::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+0263} ; ɣ
}
Return

; QWERTY H
#if
SC023::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0068} ; h
} else {
  Send {Blind}{U+0048} ; H
}
Return
+SC023::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0048} ; H
} else {
  Send {Blind}{U+0068} ; h
}
Return
>!<^SC023::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+02b0} ; ʰ
} else {
}
Return
+>!<^SC023::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+02b0} ; ʰ
}
Return

; QWERTY J
#if
SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006a} ; j
} else {
  Send {Blind}{U+004a} ; J
}
Return
+SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004a} ; J
} else {
  Send {Blind}{U+006a} ; j
}
Return
>!<^SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+02a4} ; ʤ
} else {
  Send {Blind}{U+029d} ; ʝ
}
Return
+>!<^SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+029d} ; ʝ
} else {
  Send {Blind}{U+02a4} ; ʤ
}
Return

; QWERTY K
#if
SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006b} ; k
} else {
  Send {Blind}{U+004b} ; K
}
Return
+SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004b} ; K
} else {
  Send {Blind}{U+006b} ; k
}
Return
>!<^SC025::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+03ba} ; κ
}
Return
+>!<^SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+03ba} ; κ
} else {
}
Return

; QWERTY L
#if
SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006c} ; l
} else {
  Send {Blind}{U+004c} ; L
}
Return
+SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004c} ; L
} else {
  Send {Blind}{U+006c} ; l
}
Return
>!<^SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+026b} ; ɫ
} else {
  Send {Blind}{U+2192} ; →
}
Return
+>!<^SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+2192} ; →
} else {
  Send {Blind}{U+026b} ; ɫ
}
Return

; QWERTY ;
#if
SC027::Send {Blind}{U+003b} ; ;
+SC027::Send {Blind}{U+003a} ; :
>!<^SC027::Send {Blind}{U+02d0} ; ː
+>!<^SC027::Send {Blind}{U+0300} ; ̀

; QWERTY '
#if
SC028::Send {Blind}{U+0027} ; '
+SC028::Send {Blind}{U+0040} ; @
>!<^SC028::Send {Blind}{U+031a} ; ̚
+>!<^SC028::Send {Blind}{U+0301} ; ́

; QWERTY \
#if
SC02b::Send {Blind}{U+0023} ; #
+SC02b::Send {Blind}{U+007e} ; ~
>!<^SC02b::Send {Blind}{U+005c} ; \
+>!<^SC02b::Send {Blind}{U+007c} ; |

; QWERTY Z
#if
SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+007a} ; z
} else {
  Send {Blind}{U+005a} ; Z
}
Return
+SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+005a} ; Z
} else {
  Send {Blind}{U+007a} ; z
}
Return
>!<^SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0292} ; ʒ
} else {
}
Return
+>!<^SC02c::
if not GetKeyState("CapsLock", "T") {
} else {
  Send {Blind}{U+0292} ; ʒ
}
Return

; QWERTY X
#if
SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0078} ; x
} else {
  Send {Blind}{U+0058} ; X
}
Return
+SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0058} ; X
} else {
  Send {Blind}{U+0078} ; x
}
Return
>!<^SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+03c7} ; χ
} else {
  Send {Blind}{U+03a7} ; Χ
}
Return
+>!<^SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+03a7} ; Χ
} else {
  Send {Blind}{U+03c7} ; χ
}
Return

; QWERTY C
#if
SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0063} ; c
} else {
  Send {Blind}{U+0043} ; C
}
Return
+SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0043} ; C
} else {
  Send {Blind}{U+0063} ; c
}
Return
>!<^SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+02a7} ; ʧ
} else {
  Send {Blind}{U+0254} ; ɔ
}
Return
+>!<^SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0254} ; ɔ
} else {
  Send {Blind}{U+02a7} ; ʧ
}
Return

; QWERTY V
#if
SC02f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0076} ; v
} else {
  Send {Blind}{U+0056} ; V
}
Return
+SC02f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0056} ; V
} else {
  Send {Blind}{U+0076} ; v
}
Return
>!<^SC02f::Send {Blind}{U+028c} ; ʌ
+>!<^SC02f::Send {Blind}{U+028c} ; ʌ

; QWERTY B
#if
SC030::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0062} ; b
} else {
  Send {Blind}{U+0042} ; B
}
Return
+SC030::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0042} ; B
} else {
  Send {Blind}{U+0062} ; b
}
Return
>!<^SC030::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+03b2} ; β
} else {
  Send {Blind}{U+0253} ; ɓ
}
Return
+>!<^SC030::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0253} ; ɓ
} else {
  Send {Blind}{U+03b2} ; β
}
Return

; QWERTY N
#if
SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006e} ; n
} else {
  Send {Blind}{U+004e} ; N
}
Return
+SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004e} ; N
} else {
  Send {Blind}{U+006e} ; n
}
Return
>!<^SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+014b} ; ŋ
} else {
  Send {Blind}{U+014a} ; Ŋ
}
Return
+>!<^SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+014a} ; Ŋ
} else {
  Send {Blind}{U+014b} ; ŋ
}
Return

; QWERTY M
#if
SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006d} ; m
} else {
  Send {Blind}{U+004d} ; M
}
Return
+SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004d} ; M
} else {
  Send {Blind}{U+006d} ; m
}
Return
>!<^SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+026f} ; ɯ
} else {
  Send {Blind}{U+262f} ; ☯
}
Return
+>!<^SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+262f} ; ☯
} else {
  Send {Blind}{U+026f} ; ɯ
}
Return

; QWERTY ,
#if
SC033::Send {Blind}{U+002c} ; ,
+SC033::Send {Blind}{U+003c} ; <
>!<^SC033::Send {Blind}{U+2190} ; ←
+>!<^SC033::Send {Blind}{U+2191} ; ↑

; QWERTY .
#if
SC034::Send {Blind}{U+002e} ; .
+SC034::Send {Blind}{U+003e} ; >
>!<^SC034::Send {Blind}{U+2192} ; →
+>!<^SC034::Send {Blind}{U+2193} ; ↓

; QWERTY /
#if
SC035::Send {Blind}{U+002f} ; /
+SC035::Send {Blind}{U+003f} ; ?
>!<^SC035::Send {Blind}{U+0323} ; ̣
+>!<^SC035::Send {Blind}{U+00bf} ; ¿

; QWERTY Space
#if
SC039::Send {Blind}{U+0020} ;  
+SC039::Send {Blind}{U+0020} ;  
>!<^SC039::Return
+>!<^SC039::Return

; QWERTY Iso
#if
SC056::Send {Blind}{U+005c} ; \
+SC056::Send {Blind}{U+007c} ; |
>!<^SC056::Send {Blind}{U+02c8} ; ˈ
+>!<^SC056::Send {Blind}{U+02cc} ; ˌ

; QWERTY KP_Dec
#if
SC053::Send {Blind}{U+002e} ; .
+SC053::Send {Blind}{U+002e} ; .
>!<^SC053::Return
+>!<^SC053::Return
